version: '3.9'

services:
  app:
    container_name: app
    build: ./
    image: 'docker-spring-boot-postgres:latest'
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ibm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ibm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: